window.onload = () => {
    console.log("Load")
    let select = document.getElementsByClassName("wpcf7-custom-select-list")[0];
    refreshOptions(list, select);
    let input = document.getElementsByClassName("wpcf7-custom-select-input")[0];
    input.onkeyup = typeRefresh;
};

function typeRefresh(event) {
    let select = document.getElementsByClassName("wpcf7-custom-select-list")[0];
    let search = event.target.value;
    refreshOptions(filterList(search), select)
}

function refreshOptions(optionList, root) {
    while(root.hasChildNodes()) {
        if (root.firstChild.className.includes("ul")) continue;
        root.removeChild(root.firstChild);
    }
    optionList.forEach(opt => appendOption(opt, root));
    if (optionList.length == 0) appendOption("Nincs ilyen nevű találat", root, true);
}

function appendOption(name, root, skip) {
    let option = document.createElement("li");
    option.innerHTML = name;
    if(!skip) option.onclick = selectElement;
    root.appendChild(option);
}

function filterList(search) {
    if(!search) return list;
    return list.filter(value => value.toLowerCase().includes(search.toLowerCase()));
}

function selectElement(event) {
    for (let item of document.getElementsByTagName("li")) {
        item.classList.remove("wpcf7-custom-select-list-selection")
    }
    event.target.classList.add("wpcf7-custom-select-list-selection");
    let input = document.getElementsByClassName("wpcf7-custom-select-input")[0];
    input.value = event.target.innerHTML;
}

const list = ["Szent Mór Katolikus Óvoda, Általános Iskola, Alapfokú Művészeti Iskola és Gimnázium - Pécs",
"Ciszterci Rend Nagy Lajos Gimnáziuma és Kollégiuma - Pécs",
"Pécsi Leőwey Klára Gimnázium - Pécs",
"Pécsi Kodály Zoltán Gimnázium - Pécs",
"Pécsi Apáczai Csere János Általános Iskola, Gimnázium, Kollégium, Alapfokú Művészeti Iskola - Pécs",
"Mohácsi Kisfaludy Károly Gimnázium - Mohács",
"Siklósi Táncsics Mihály Gimnázium, Általános Iskola és Alapfokú Művészeti Iskola - Siklós",
"Pécsi Tudományegyetem Gyakorló Általános Iskola, Gimnázium és Óvoda - Pécs",
"Pécsi Janus Pannonius Gimnázium - Pécs",
"Pécsi Református Kollégium Gimnáziuma, Általános Iskolája, Óvodája és Alapfokú Művészeti Iskolája - Pécs",
"Gandhi Gimnázium, Kollégium, Általános Iskola és Alapfokú Művészeti Iskola - Pécs",
"Baptista Szeretetszolgálat EJSZ Széchenyi István Gimnáziuma és Technikuma - Pécs",
"Pécsi Művészeti Gimnázium, Szakgimnázium és Technikum - Pécs",
"Nagyasszonyunk Katolikus Óvoda, Általános Iskola és Gimnázium - Kalocsa",
"Tiszakécskei Református Általános Iskola és Gimnázium - Tiszakécske",
"Dunavecsei Református Kollégium - Óvoda, Általános Iskola, Középiskola, és Kollégium - Dunavecse",
"Bajai III. Béla Gimnázium - Baja",
"Magyarországi Németek Általános Művelődési Központja - Baja",
"Bácsalmási Hunyadi János Gimnázium - Bácsalmás",
"Kalocsai Szent István Gimnázium - Kalocsa",
"Kecskeméti Bányai Júlia Gimnázium - Kecskemét",
"Kecskeméti Katona József Gimnázium - Kecskemét",
"Kecskeméti Bolyai János Gimnázium - Kecskemét",
"Kiskunfélegyházi Móra Ferenc Gimnázium - Kiskunfélegyháza",
"Baksay Sándor Református Gimnázium és Általános Iskola - Kunszentmiklós",
"Piarista Gimnázium, Kollégium, Általános Iskola és Óvoda - Kecskemét",
"Kiskunhalasi Bibó István Gimnázium - Kiskunhalas",
"Kecskeméti Református Gimnázium - Kecskemét",
"Tiszakécskei Móricz Zsigmond Általános Iskola, Gimnázium, Kollégium és Alapfokú Művészeti Iskola - Tiszakécske",
"Kiskunhalasi Református Kollégium Szilády Áron Gimnázium és Kollégium - Kiskunhalas",
"Szent László Általános Művelődési Központ - Baja",
"Orosházi Táncsics Mihály Gimnázium és Kollégium - Orosháza",
"Székács József Evangélikus Óvoda, Általános Iskola és Gimnázium - Orosháza",
"Szent Gellért Katolikus Általános Iskola és Gimnázium - Gyomaendrőd",
"Békéscsabai Andrássy Gyula Gimnázium és Kollégium - Békéscsaba",
"Mezőberényi Petőfi Sándor Evangélikus Gimnázium, Kollégium és Általános Iskola - Mezőberény",
"Mezőkovácsházi Hunyadi János Általános Iskola, Gimnázium és Kollégium - Mezőkovácsháza",
"Gyulai Erkel Ferenc Gimnázium és Kollégium - Gyula",
"Ady Endre-Bay Zoltán Gimnázium és Kollégium - Sarkad",
"NICOLAE BĂLCESCU ROMÁN GIMNÁZIUM, ÁLTALÁNOS ISKOLA ÉS KOLLÉGIUM - Gyula",
"Gyulai Római Katolikus Gimnázium, Általános Iskola, Óvoda és Kollégium - Gyula",
"Békéscsabai Belvárosi Általános Iskola és Gimnázium - Békéscsaba",
"Szeberényi Gusztáv Adolf Evangélikus Gimnázium, Technikum, Szakgimnázium, Általános Iskola, Óvoda, Alapfokú Művészeti Iskola és Kollégium - Békéscsaba",
"Jankó János Általános Iskola és Gimnázium - Tótkomlós",
"Szegedi Kis István Református Gimnázium, Technikum, Általános Iskola, Óvoda és Kollégium - Békés",
"Fráter György Katolikus Gimnázium és Kollégium - Miskolc",
"Hámori Waldorf Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Miskolc",
"Nebuló Általános Iskola és Gimnázium - Miskolc",
"Miskolci Herman Ottó Gimnázium - Miskolc",
"Diósgyőri Gimnázium - Miskolc",
"Miskolci Zrínyi Ilona Gimnázium - Miskolc",
"Avasi Gimnázium - Miskolc",
"Tiszaújvárosi Eötvös József Gimnázium és Kollégium - Tiszaújváros",
"Sárospataki Árpád Vezér Gimnázium és Kollégium - Sárospatak",
"Lévay József Református Gimnázium és Diákotthon - Miskolc",
"Földes Ferenc Gimnázium - Miskolc",
"Bethlen Gábor Református Gimnázium és Szathmáry Kollégium - Hódmezővásárhely",
"Horváth Mihály Gimnázium - Szentes",
"Szegedi Tudományegyetem Gyakorló Gimnázium és Általános Iskola - Szeged",
"Szegedi Radnóti Miklós Kísérleti Gimnázium - Szeged",
"Szegedi Deák Ferenc Gimnázium - Szeged",
"Makói József Attila Gimnázium - Makó",
"Szegedi Tömörkény István Gimnázium, Művészeti Szakgimnázium és Technikum - Szeged",
"Dugonics András Piarista Gimnázium, Alapfokú Művészeti Iskola és Kollégium - Szeged",
"Székesfehérvári Kodály Zoltán Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Székesfehérvár",
"Comenius Angol-Magyar Két Tanítási Nyelvű Gimnázium, Általános Iskola, Óvoda és Technikum - Székesfehérvár",
"Szent Imre Gimnázium, Általános Iskola és Óvoda - Székesfehérvár",
"Chernel István Általános Iskola és Gimnázium - Gárdony",
"Kápolnásnyéki Vörösmarty Mihály Általános Iskola és Gimnázium - Kápolnásnyék",
"Dunaújvárosi Rosti Pál Gimnázium és Általános Iskola - Dunaújváros",
"Dunaújvárosi Széchenyi István Gimnázium - Dunaújváros",
"Móri Táncsics Mihály Gimnázium - Mór",
"Ciszterci Szent István Gimnázium - Székesfehérvár",
"Tóparti Gimnázium és Művészeti Szakgimnázium - Székesfehérvár",
"Sárbogárdi Petőfi Sándor Gimnázium - Sárbogárd",
"Székesfehérvári Teleki Blanka Gimnázium és Általános Iskola - Székesfehérvár",
"Lánczos Kornél Gimnázium - Székesfehérvár",
"Kodolányi János Gimnázium - Székesfehérvár",
"Páli Szent Vince Katolikus Gimnázium, Általános Iskola és Óvoda - Kapuvár",
"Piarista Gimnázium, Általános Iskola és Óvoda - Mosonmagyaróvár",
"Szabadhegyi Magyar-Német Két Tanítási Nyelvű Általános Iskola és Gimnázium - Győr",
"Péterfy Sándor Evangélikus Gimnázium, Általános Iskola, Óvoda, Alapfokú Művészeti Iskola és Kollégium - Győr",
"Prohászka Ottokár Orsolyita Gimnázium, Általános Iskola és Óvoda - Győr",
"Berzsenyi Dániel Evangélikus (Líceum) Gimnázium és Kollégium - Sopron",
"Soproni Széchenyi István Gimnázium - Sopron",
"Révai Miklós Gimnázium és Kollégium - Győr",
"Kazinczy Ferenc Gimnázium és Kollégium - Győr",
"Pannonhalmi Bencés Gimnázium és Szakkollégium - Pannonhalma",
"Czuczor Gergely Bencés Gimnázium és Kollégium - Győr",
"Mosonmagyaróvári Kossuth Lajos Gimnázium és Kollégium - Mosonmagyaróvár",
"Eötvös József Evangélikus Gimnázium, Egészségügyi Technikum és Művészeti Szakgimnázium - Sopron",
"Szent Orsolya Római Katolikus Gimnázium, Általános Iskola, Óvoda és Kollégium - Sopron",
"Apor Vilmos Római Katolikus Óvoda, Általános Iskola, Alapfokú Művészeti Iskola, Gimnázium és Kollégium - Győr",
"Svetits Katolikus Óvoda, Általános Iskola, Gimnázium és Kollégium - Debrecen",
"Napraforgó Waldorf Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Debrecen",
"II. Rákóczi Ferenc Általános Iskola, Gimnázium, Szakképző Iskola, Alapfokú Művészeti Iskola és Óvoda - Hajdúsámson",
"Debreceni Csokonai Vitéz Mihály Gimnázium - Debrecen",
"Debreceni Fazekas Mihály Gimnázium - Debrecen",
"Tóth Árpád Gimnázium - Debrecen",
"Debreceni Egyetem Kossuth Lajos Gyakorló Gimnáziuma és Általános Iskolája - Debrecen",
"Debreceni Ady Endre Gimnázium - Debrecen",
"Medgyessy Ferenc Gimnázium, Művészeti Szakgimnázium és Technikum - Debrecen",
"Derecskei I. Rákóczi György Gimnázium,Technikum és Kollégium - Derecske",
"Hajdúböszörményi Bocskai István Gimnázium - Hajdúböszörmény",
"Hőgyes Endre Gimnázium - Hajdúszoboszló",
"Debreceni Református Kollégium Gimnáziuma és Diákotthona - Debrecen",
"Gyöngyösi Berze Nagy János Gimnázium - Gyöngyös",
"Egri Szilágyi Erzsébet Gimnázium és Kollégium - Eger",
"Egri Dobó István Gimnázium - Eger",
"Neumann János Gimnázium, Technikum és Kollégium - Eger",
"Egri Pásztorvölgyi Általános Iskola és Gimnázium - Eger",
"Gárdonyi Géza Ciszterci Gimnázium és Kollégium - Eger",
"Színes Iskola - Személyközpontú Óvoda, Általános Iskola és Gimnázium - Tata",
"Szent Margit Gimnázium és Általános Iskola - Tatabánya",
"Kisbéri Táncsics Mihály Gimnázium és Általános Iskola - Kisbér",
"Komáromi Jókai Mór Gimnázium - Komárom",
"Hamvas Béla Gimnázium - Oroszlány",
"Temesvári Pelbárt Ferences Gimnázium és Kollégium - Esztergom",
"Tatabányai Árpád Gimnázium - Tatabánya",
"Esztergomi Dobó Katalin Gimnázium - Esztergom",
"Árpád-házi Szent Erzsébet Gimnázium, Óvoda és Általános Iskola - Esztergom",
"Balassagyarmati Balassi Bálint Gimnázium - Balassagyarmat",
"Nógrád Megyei Váci Mihály Gimnázium - Bátonyterenye",
"Salgótarjáni Bolyai János Gimnázium - Salgótarján",
"Mikszáth Kálmán Gimnázium és Kollégium - Pásztó",
"Szent Imre Katolikus Általános Iskola és Gimnázium - Balassagyarmat",
"Salgótarjáni Madách Imre Gimnázium - Salgótarján",
"Péceli Integrált Oktatási Központ Általános Iskola és Gimnázium - Pécel",
"Sashegyi Sándor Általános Iskola és Gimnázium - Pomáz",
"Páduai Szent Antal Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Piliscsaba",
"Prohászka Ottokár Katolikus Gimnázium - Budakeszi",
"Zsámbéki Premontrei Keresztelő Szent János Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Zsámbék",
"Budakeszi Nagy Sándor József Gimnázium - Budakeszi",
"Ceglédi Kossuth Lajos Gimnázium - Cegléd",
"Dunakeszi Radnóti Miklós Gimnázium - Dunakeszi",
"Érdi Vörösmarty Mihály Gimnázium - Érd",
"Ócsai Bolyai János Gimnázium - Ócsa",
"Ráckevei Ady Endre Gimnázium - Ráckeve",
"Szentendrei Móricz Zsigmond Gimnázium - Szentendre",
"Váci Madách Imre Gimnázium - Vác",
"Dabasi Táncsics Mihály Gimnázium - Dabas",
"Gödöllői Török Ignác Gimnázium - Gödöllő",
"József Attila Gimnázium és Közgazdasági Szakgimnázium - Monor",
"Damjanich János Gimnázium és Mezőgazdasági Technikum - Nagykáta",
"Arany János Református Gimnázium, Technikum és Kollégium - Nagykőrös",
"Baktay Ervin Gimnázium - Dunaharaszti",
"Szigetszentmiklósi Batthyány Kázmér Gimnázium - Szigetszentmiklós",
"Piarista Gimnázium és Kollégium - Vác",
"Gödöllői Református Líceum Gimnázium - Gödöllő",
"Szent László Gimnázium, Technikum, Szakképző Iskola és Kollégium - Szob",
"Szentendrei II. Rákóczi Ferenc Általános Iskola és Gimnázium - Szentendre",
"Aszódi Evangélikus Petőfi Gimnázium, Általános Iskola és Kollégium - Aszód",
"Teleki László Gimnázium - Gyömrő",
"Százhalombattai Arany János Általános Iskola és Gimnázium - Százhalombatta",
"Fóti Népművészeti Szakgimnázium és Gimnázium - Fót",
"Bocskai István Református Oktatási Központ - Óvoda, Általános Iskola, Gimnázium, Technikum, Szakgimnázium, Szakképző Iskola, Alapfokú Művészeti Iskola és Kollégium - Halásztelek",
"Bálint Márton Általános Iskola és Középiskola - Törökbálint",
"Kinizsi Pál Gimnázium - Abony",
"Gábor Dénes Óvoda, Általános Iskola, Gimnázium és Technikum - Isaszeg",
"Budakalász Gimnázium - Budakalász",
"Várday Kata Református Általános Iskola, Gimnázium és Kollégium - Kisvárda",
"Waldorf Óvoda, Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Nyíregyháza",
"Demecseri Oktatási Centrum Gimnázium, Általános Iskola, Alapfokú Művészeti Iskola - Demecser",
"Fehérgyarmati Deák Ferenc Általános Iskola, Gimnázium és Kollégium - Fehérgyarmat",
"Kisvárdai Bessenyei György Gimnázium és Kollégium - Kisvárda",
"Korányi Frigyes Görögkatolikus Általános Iskola, Gimnázium és Kollégium - Nagykálló",
"Nyíregyházi Evangélikus Kossuth Lajos Gimnázium - Nyíregyháza",
"Nyíregyházi Krúdy Gyula Gimnázium - Nyíregyháza",
"Nyíregyházi Zrínyi Ilona Gimnázium és Kollégium - Nyíregyháza",
"Nyíregyházi Kölcsey Ferenc Gimnázium - Nyíregyháza",
"Nyíregyházi Vasvári Pál Gimnázium - Nyíregyháza",
"Vásárosnaményi II. Rákóczi Ferenc Gimnázium - Vásárosnamény",
"Mátészalkai Esze Tamás Gimnázium - Mátészalka",
"Báthory István Katolikus Óvoda, Két Tanítási Nyelvű Általános Iskola és Gimnázium - Nyírbátor",
"Szent László Katolikus Gimnázium, Technikum, Két Tanítási Nyelvű Általános Iskola, Kollégium és Óvoda - Kisvárda",
"Szent Imre Katolikus Gimnázium, Két Tanítási Nyelvű Általános Iskola, Kollégium, Óvoda és Alapfokú Művészeti Iskola - Nyíregyháza",
"Nyíregyházi Arany János Gimnázium, Általános Iskola és Kollégium - Nyíregyháza",
"Nyíregyházi Egyetem Eötvös József Gyakorló Általános Iskola és Gimnázium - Nyíregyháza",
"Ecsedi Báthori István Református Általános Iskola és Gimnázium - Nagyecsed",
"Lorántffy Zsuzsanna Református Óvoda, Általános Iskola, Gimnázium és Kollégium - Kaposvár",
"Kaposvári Táncsics Mihály Gimnázium - Kaposvár",
"Kaposvári Csokonai Vitéz Mihály Általános Iskola, Gimnázium és Szakgimnázium - Kaposvár",
"Mátyás Király Gimnázium - Fonyód",
"Marcali Berzsenyi Dániel Gimnázium - Marcali",
"Kaposvári Munkácsy Mihály Gimnázium - Kaposvár",
"Siófoki Perczel Mór Gimnázium és Kollégium - Siófok",
"Nagyboldogasszony Római Katolikus Gimnázium, Általános Iskola és Alapfokú Művészeti Iskola - Kaposvár",
"Csokonai Vitéz Mihály Református Gimnázium, Általános Iskola és Kollégium - Csurgó",
"Szent II. János Pál Óvoda, Általános Iskola és Gimnázium - Budapest XI. kerület",
"Csik Ferenc Általános Iskola és Gimnázium - Budapest II. kerület",
"Budenz József Általános Iskola és Gimnázium - Budapest II. kerület",
"Budapest III. Kerületi Kerék Általános Iskola és Gimnázium - Budapest III. kerület",
"Szent József Katolikus Óvoda, Általános Iskola és Gimnázium - Budapest III. kerület",
"Óbudai Waldorf Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Budapest III. kerület",
"Újpesti Károlyi István Általános Iskola és Gimnázium - Budapest IV. kerület",
"Újpesti Bródy Imre Gimnázium és Általános Iskola - Budapest IV. kerület",
"Újpesti Csokonai Vitéz Mihály Általános Iskola és Gimnázium - Budapest IV. kerület",
"Deák Diák Ének-zenei Általános Iskola és Gimnázium - Budapest VIII. kerület",
"Budapesti Ward Mária Általános Iskola, Gimnázium és Zeneművészeti Szakgimnázium - Budapest V. kerület",
"Lauder Javne Zsidó Közösségi Óvoda, Általános Iskola, Gimnázium és Zenei Alapfokú Művészeti Iskola - Budapest XII. kerület",
"Lónyay Utcai Református Gimnázium és Kollégium - Budapest IX. kerület",
"Újbudai József Attila Gimnázium - Budapest XI. kerület",
"Greater Grace Nemzetközi Óvoda, Általános Iskola és Gimnázium - Budapest XII. kerület",
"Budapesti Nemzetközi Iskola-International School of Budapest és Magyar-Angol Két Tanítási Nyelvű Általános Iskola és Gimnázium - Budapest XII. kerület",
"Budapest XV. Kerületi László Gyula Gimnázium és Általános Iskola - Budapest XV. kerület",
"Bornemisza Péter Gimnázium, Általános Iskola, Alapfokú Művészeti Iskola, Óvoda és Sportiskola - Budapest X. kerület",
"Pál Apostol Katolikus Óvoda, Általános Iskola és Gimnázium - Budapest XVII. kerület",
"Kispesti Waldorf Óvoda, Általános Iskola, Alapfokú Művészeti Iskola és Gimnázium - Budapest XIX. kerület",
"Burattino Általános és Középiskola, Gyermekotthon - Budapest XXI. kerület",
"Rózsakerti Demjén István Református Általános Iskola és Gimnázium - Budapest XXII. kerület",
"Fővárosi Iskolaszanatórium Általános Iskola és Gimnázium - Budapest III. kerület",
"Budapest I. Kerületi Petőfi Sándor Gimnázium - Budapest I. kerület",
"Budapest I. Kerületi Szilágyi Erzsébet Gimnázium - Budapest I. kerület",
"Budapest I. Kerületi Toldy Ferenc Gimnázium - Budapest I. kerület",
"Budapest II. Kerületi II. Rákóczi Ferenc Gimnázium - Budapest II. kerület",
"Óbudai Árpád Gimnázium - Budapest III. kerület",
"Óbudai Gimnázium - Budapest III. kerület",
"Békásmegyeri Veres Péter Gimnázium - Budapest III. kerület",
"Újpesti Könyves Kálmán Gimnázium - Budapest IV. kerület",
"Újpesti Babits Mihály Gimnázium - Budapest IV. kerület",
"ELTE Apáczai Csere János Gyakorló Gimnázium és Kollégium - Budapest V. kerület",
"Budapest V. Kerületi Eötvös József Gimnázium - Budapest V. kerület",
"Veres Pálné Gimnázium - Budapest V. kerület",
"Budapest VI. Kerületi Kölcsey Ferenc Gimnázium - Budapest VI. kerület",
"VII. Kerületi Madách Imre Gimnázium - Budapest VII. kerület",
"Budapest VIII. Kerületi Vörösmarty Mihály Gimnázium - Budapest VIII. kerület",
"Budapest IX. Kerületi Leövey Klára Gimnázium - Budapest IX. kerület",
"Kőbányai Szent László Gimnázium - Budapest X. kerület",
"Budapest X. Kerületi Zrínyi Miklós Gimnázium - Budapest X. kerület",
"Szent Margit Gimnázium - Budapest XI. kerület",
"Városmajori Gimnázium - Budapest XII. kerület",
"Berzsenyi Dániel Gimnázium - Budapest XIII. kerület",
"Németh László Gimnázium - Budapest XIII. kerület",
"Budapest XIII. Kerületi Ady Endre Gimnázium - Budapest XIII. kerület",
"Szent István Gimnázium - Budapest XIV. kerület",
"Budapest XIV. Kerületi Teleki Blanka Gimnázium - Budapest XIV. kerület",
"Budapest XV. Kerületi Dózsa György Gimnázium és Táncművészeti Szakgimnázium - Budapest XV. kerület",
"Budapest XVI. Kerületi Szerb Antal Gimnázium - Budapest XVI. kerület",
"Budapest XVII. Kerületi Balassi Bálint Nyolcévfolyamos Gimnázium - Budapest XVII. kerület",
"Karinthy Frigyes Gimnázium - Budapest XVIII. kerület",
"Kispesti Deák Ferenc Gimnázium - Budapest XIX. kerület",
"Kispesti Károlyi Mihály Magyar-Spanyol Tannyelvű Gimnázium - Budapest XIX. kerület",
"Jedlik Ányos Gimnázium - Budapest XXI. kerület",
"Budapest XXII. Kerületi Budai Nagy Antal Gimnázium - Budapest XXII. kerület",
"Kempelen Farkas Gimnázium - Budapest XXII. kerület",
"Piarista Gimnázium - Budapest V. kerület",
"Patrona Hungariae Óvoda, Általános Iskola, Gimnázium, Kollégium és Alapfokú Művészeti Iskola - Budapest IX. kerület",
"Budapest-Fasori Evangélikus Gimnázium - Budapest VII. kerület",
"Magyar Táncművészeti Egyetem Nádasi Ferenc Gimnáziuma és Kollégiuma - Budapest XIV. kerület",
"Budapest VI. Kerületi Szinyei Merse Pál Gimnázium - Budapest VI. kerület",
"Nikola Tesla Szerb Tanítási Nyelvű Óvoda, Általános Iskola, Gimnázium, Kollégium és Könyvtár - Budapest VII. kerület",
"Budapesti Fazekas Mihály Gyakorló Általános Iskola és Gimnázium - Budapest VIII. kerület",
"Szlovák Tanítási Nyelvű Óvoda, Általános Iskola, Gimnázium és Kollégium - Budapest XIII. kerület",
"ELTE Trefort Ágoston Gyakorló Gimnázium - Budapest VIII. kerület",
"Corvin Mátyás Gimnázium - Budapest XVI. kerület",
"Budapest IX. Kerületi Szent-Györgyi Albert Általános Iskola és Gimnázium - Budapest IX. kerület",
"Ferencvárosi Sport Általános Iskola és Gimnázium - Budapest IX. kerület",
"Budapest IX. Kerületi Weöres Sándor Általános Iskola és Gimnázium - Budapest IX. kerület",
"Tamási Áron Általános Iskola, Gimnázium és Német Nemzetiségi Gimnázium - Budapest XII. kerület",
"Sashegyi Arany János Általános Iskola és Gimnázium - Budapest XII. kerület",
"Budapesti Osztrák Iskola - Osztrák Felsőreál Gimnázium - Budapest XII. kerület",
"Német Nemzetiségi Gimnázium és Kollégium - Budapest XX. kerület",
"Baár-Madas Református Gimnázium, Általános Iskola és Kollégium - Budapest II. kerület",
"Kodály Zoltán Magyar Kórusiskola Katolikus Általános Iskola, Gimnázium, Alapfokú Művészeti Iskola és Szakgimnázium - Budapest I. kerület",
"Budapest XVI. Kerületi Táncsics Mihály Általános Iskola és Gimnázium - Budapest XVI. kerület",
"Jerikó Keresztény Humán Gimnázium és Pedagógiai Szakgimnázium - Budapest XIX. kerület",
"Európa Alapítvány Középfokú Intézet (EAKI)Gimnázium - Budapest XIII. kerület",
"Álmos Vezér Gimnázium, Pedagógiai Szakgimnázium és Általános Iskola - Budapest XIV. kerület",
"Budenz József Alapítványi Gimnázium - Budapest II. kerület",
"Kürt Alapítványi Gimnázium - Budapest XI. kerület",
"Budapest XVII. Kerületi Kőrösi Csoma Sándor Általános Iskola és Gimnázium - Budapest XVII. kerület",
"Deák Téri Evangélikus Gimnázium - Budapest V. kerület",
"Budapest XVIII. Kerületi Vörösmarty Mihály Ének-zenei, Nyelvi Általános Iskola és Gimnázium - Budapest XVIII. kerület",
"Budapest XX. Kerületi Kossuth Lajos Gimnázium - Budapest XX. kerület",
"Budapest XX. Kerületi Nagy László Általános Iskola és Gimnázium - Budapest XX. kerület",
"Horvát Óvoda, Általános Iskola, Gimnázium és Kollégium - Budapest XIV. kerület",
"Klebelsberg Kuno Általános Iskola és Gimnázium - Budapest II. kerület",
"Bethlen Gábor Általános Iskola és Gimnázium - Budapest XI. kerület",
"Kontyfa Általános Iskola és Gimnázium - Budapest XV. kerület",
"Pasaréti Gimnázium - Budapest II. kerület",
"Budapest I. Kerületi Kosztolányi Dezső Gimnázium - Budapest I. kerület",
"Pesthidegkúti Waldorf Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Budapest II. kerület",
"Pasaréti Szabó Lőrinc Magyar-Angol Két Tanítási Nyelvű Általános Iskola és Gimnázium - Budapest II. kerület",
"BME által alapított Két Tanítási Nyelvű Gimnázium - Budapest XI. kerület",
"Gustave Eiffel Francia Óvoda, Általános Iskola és Gimnázium - Budapest II. kerület",
"Budapesti Egyetemi Katolikus Gimnázium és Kollégium - Budapest I. kerület",
"Szent Gellért Katolikus Általános Iskola és Gimnázium - Budapest I. kerület",
"Kodály Zoltán Ének-zenei Általános Iskola, Gimnázium és Zenei Alapfokú Művészeti Iskola - Budapest II. kerület",
"Budai Ciszterci Szent Imre Gimnázium - Budapest XI. kerület",
"Alternatív Közgazdasági Gimnázium, Szakgimnázium és Általános Iskola - Budapest III. kerület",
"Közgazdasági Politechnikum Alternatív Gimnázium - Budapest IX. kerület",
"Budapest Baptista Gimnázium,Technikum és Sportiskola - Budapest XX. kerület",
"Xántus János Két Tanítási Nyelvű Gimnázium - Budapest V. kerület",
"Európa 2000 Gimnázium - Budapest XIV. kerület",
"ADDETUR Baptista Gimnázium, Technikum és Szakiskola - Budapest II. kerület",
"Pestszentlőrinc-Pestszentimrei Felnőttek Általános Iskolája és Gimnáziuma - Budapest XVIII. kerület",
"Belvárosi Tanoda Alapítványi Gimnázium - Budapest V. kerület",
"Szent István Sport Általános Iskola és Gimnázium - Jászberény",
"Jászberényi Nagyboldogasszony Katolikus Óvoda, Kéttannyelvű Általános Iskola és Gimnázium - Jászberény",
"Aranyos Szeglet Waldorf Óvoda, Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Szolnok",
"Deák Ferenc Gimnázium, Közgazdasági és Informatikai Szakgimnázium - Jászárokszállás",
"Varga Katalin Gimnázium - Szolnok",
"Verseghy Ferenc Gimnázium - Szolnok",
"Szolnoki Széchenyi István Gimnázium és Művészeti Szakgimnázium - Szolnok",
"Mezőtúri Református Kollégium, Gimnázium, Technikum, Általános Iskola és Óvoda - Mezőtúr",
"Humán Intézet Gimnázium és Alapfokú Művészeti Iskola - Budapest VII. kerület",
"Kossuth Lajos Gimnázium és Általános Iskola - Tiszafüred",
"Bonyhádi Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Bonyhád",
"Paksi Balogh Antal Katolikus Óvoda, Általános Iskola és Gimnázium - Paks",
"Hőgyészi Hegyhát Általános Iskola, Gimnázium és Kollégium - Hőgyész",
"Vak Bottyán Általános Iskola és Gimnázium - Simontornya",
"Bonyhádi Petőfi Sándor Evangélikus Gimnázium, Kollégium, Általános Iskola és Alapfokú Művészeti Iskola - Bonyhád",
"Dombóvári Illyés Gyula Gimnázium - Dombóvár",
"Szekszárdi Garay János Gimnázium - Szekszárd",
"Tolnai Szent István Katolikus Gimnázium - Tolna",
"Paksi Vak Bottyán Gimnázium - Paks",
"Szekszárdi I. Béla Gimnázium, Kollégium és Általános Iskola - Szekszárd",
"Szekszárdi Kolping Katolikus Szakképző Iskola, Gimnázium és Alapfokú Művészeti Iskola - Szekszárd",
"Árpád-házi Szent Margit Óvoda, Általános Iskola, Gimnázium és Kollégium - Kőszeg",
"Boldog Brenner János Általános Iskola, Gimnázium és Kollégium - Szombathely",
"Celldömölki Berzsenyi Dániel Gimnázium - Celldömölk",
"Körmendi Kölcsey Ferenc Gimnázium - Körmend",
"Jurisich Miklós Gimnázium és Kollégium - Kőszeg",
"Szombathelyi Nagy Lajos Gimnázium - Szombathely",
"Szombathelyi Kanizsai Dorottya Gimnázium - Szombathely",
"Premontrei Rendi Szent Norbert Gimnázium - Szombathely",
"ELTE Bolyai János Gyakorló Általános Iskola és Gimnázium - Szombathely",
"Magyar-Angol Tannyelvű Gimnázium és Kollégium - Balatonalmádi",
"Lóczy Lajos Gimnázium - Balatonfüred",
"Kisfaludy Sándor Gimnázium, Kollégium és Alapfokú Művészeti Iskola - Sümeg",
"Lovassy László Gimnázium - Veszprém",
"Vetési Albert Gimnázium - Veszprém",
"III. Béla Gimnázium, Művészeti Szakgimnázium és Alapfokú Művészeti Iskola - Zirc",
"Pápai Petőfi Sándor Gimnázium - Pápa",
"Pápai Református Kollégium Gimnáziuma, Művészeti Szakgimnáziuma és Diákotthona - Pápa",
"Ajkai Bródy Imre Gimnázium - Ajka",
"Türr István Gimnázium és Kollégium - Pápa",
"Noszlopy Gáspár Gimnázium és Kollégium - Veszprém",
"Batsányi János Gimnázium és Kollégium - Tapolca",
"Érdi Gárdonyi Géza Általános Iskola és Gimnázium - Érd",
"Marianum Német Nemzetiségi Nyelvoktató Általános Iskola és Gimnázium - Érd",
"Piarista Általános Iskola, Gimnázium, Kollégium és Boldog Donáti Celesztina Óvoda - Nagykanizsa",
"Mindszenty József Általános Iskola, Gimnázium és Kollégium - Zalaegerszeg",
"Zalaegerszegi Kölcsey Ferenc Gimnázium - Zalaegerszeg",
"Gönczi Ferenc Gimnázium - Lenti",
"Zalaegerszegi Zrínyi Miklós Gimnázium - Zalaegerszeg",
"Keszthelyi Vajda János Gimnázium - Keszthely",
"Batthyány Lajos Gimnázium - Nagykanizsa",
"Dr. Mező Ferenc Gimnázium - Nagykanizsa",
"Hévízi Bibó István Gimnázium és Kollégium - Hévíz",
"Zalaegerszegi Ady Endre Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Zalaegerszeg",
"Ferences Gimnázium - Szentendre",
"Budaörsi Illyés Gyula Gimnázium, Szakgimnázium és Technikum - Budaörs",
"Budapest II. Kerületi Móricz Zsigmond Gimnázium - Budapest II. kerület",
"ELTE Radnóti Miklós Gyakorló Általános Iskola és Gyakorló Gimnázium - Budapest XIV. kerület",
"Péter András Gimnázium és Kollégium - Szeghalom",
"Székesfehérvári Vasvári Pál Gimnázium - Székesfehérvár",
"Szent József Óvoda, Általános Iskola, Gimnázium és Kollégium - Debrecen",
"Dorogi Zsigmondy Vilmos Magyar-Angol Két Tanítási Nyelvű Gimnázium - Dorog",
"Hajnóczy József Gimnázium, Humán Szakgimnázium és Kollégium - Tiszaföldvár",
"Thuri György Gimnázium és Alapfokú Művészeti Iskola - Várpalota",
"Thomas Mann Gymnasium-Deutsche Schule Budapest, Budapesti Német Általános Iskola és Gimnázium - Budapest XII. kerület",
"Fényi Gyula Jezsuita Gimnázium, Kollégium és Óvoda - Miskolc",
"Bárdos László Gimnázium - Tatabánya",
"Premontrei Szent Norbert Gimnázium, Egyházzenei Szakgimnázium, Alapfokú Művészeti Iskola és Kollégium - Gödöllő",
"Lehel Vezér Gimnázium - Jászberény",
"Padányi Biró Márton Római Katolikus Gimnázium, Technikum és Általános Iskola - Veszprém",
"Pentelei Mentálhigiénés Általános Iskola, Szakképző Iskola és Gimnázium - Dunaújváros",
"Mozgásjavító Óvoda, Általános Iskola, Gimnázium, Kollégium, Egységes Gyógypedagógiai Módszertani Intézmény - Budapest XIV. kerület",
"Sárospataki Református Kollégium Gimnáziuma, Általános Iskolája és Diákotthona - Sárospatak",
"Rajkó-Talentum Alapfokú Művészeti Iskola és Középiskola - Budapest VII. kerület",
"Hang-Szín-Tér Művészeti Gimnázium, Művészeti Szakgimnázium, Alapfokú Művészeti Iskola és Kollégium - Bodajk",
"Karolina Óvoda, Általános Iskola, Gimnázium, Alapfokú Művészeti Iskola és Kollégium - Szeged",
"Trívium Alapítványi Gimnázium - Gyöngyös",
"Constantinum Katolikus Óvoda, Általános Iskola, Gimnázium, Technikum, Kollégium - Kiskunfélegyháza",
"SEK Budapest Óvoda, Általános Iskola és Gimnázium - Budapest II. kerület",
"Budapesti Zsidó Hitközség Scheiber Sándor Gimnázium és Általános Iskola - Budapest XIV. kerület",
"Fóti Szabad Waldorf Óvoda, Általános Iskola, Alapfokú Művészeti Iskola és Gimnázium - Fót",
"Dombrádi Móra Ferenc Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Dombrád",
"Kardos István Általános Iskola, Gimnázium és Szakgimnázium - Szigetszentmiklós",
"Budapesti Nemzetközi Keresztyén Óvoda, Általános Iskola és Gimnázium - Diósd",
"Innovációs Gimnázium - Budapest XV. kerület",
"Kovács Pál Baptista Gimnázium - Budapest XV. kerület",
"Katedra Általános Iskola, Gimnázium, Informatikai és Művészeti Technikum, Szakgimnázium és Kollégium - Kecskemét",
"Szent Angéla Ferences Általános Iskola és Gimnázium - Budapest II. kerület",
"Alsóerdősori Bárdos Lajos Általános Iskola és Gimnázium - Budapest VII. kerület",
"Comenius Szakközépiskola, Szakgimnázium, Gimnázium és Alapfokú Művészeti Iskola - Budapest XIX. kerület",
"EURO Baptista Két Tanítási Nyelvű Gimnázium és Technikum - Debrecen",
"Sylvester János Református Gimnázium és Technikum - Budapest XIV. kerület",
"Szentendrei Református Gimnázium - Szentendre",
"Atalanta Gimnázium - Budapest VIII. kerület",
"Gimnázium, Informatikai, Közgazdasági, Nyomdaipari Technikum és Szakképző Iskola - Eger",
"Európai Üzleti Gimnázium - Eger",
"Forrás Waldorf Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Győr",
"Gyermekház Iskola - Budapest XIII. kerület",
"Fészek Waldorf Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Solymár",
"Zöld Kakas Líceum Mentálhigiénés Szakgimnázium, Gimnázium és Általános Iskola - Budapest IX. kerület",
"Magyar Műhely Általános Művelődési Központ - Mezőörs",
"Kalyi Jag Roma Nemzetiségi Általános Iskola, Gimnázium, Szakképző Intézmény, Alapfokú Művészeti Iskola és Felnőttoktatási Intézmény - Budapest VI. kerület",
"Britannica Angolnyelvű Nemzetközi Óvoda, Általános Iskola és Gimnázium - Budapest XII. kerület",
"Budapesti Amerikai Nemzetközi Iskola - Nagykovácsi",
"Kőrösi Csoma Sándor Két Tanítási Nyelvű Baptista Gimnázium - Budapest III. kerület",
"Perintparti Szó-Fogadó Szombathelyi Waldorf Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Szombathely",
"Abigél Általános Iskola, Alapfokú Művészeti Iskola, Szakgimnázium, Gimnázium, Kollégium, Technikum és Szakképző Iskola - Nyíregyháza",
"Szabad Waldorf Általános Iskola és Gimnázium, Alapfokú Művészeti Iskola - Szeged",
"Aranykéz Gimnázium, Technikum és Szakképző Iskola - Székesfehérvár",
"Boldog Adolf Kolping Katolikus Általános Iskola, Gimnázium és Sportgimnázium - Budapest XIII. kerület",
"Újbudai Széchenyi István Gimnázium - Budapest XI. kerület",
"Kossuth Lajos Evangélikus Óvoda, Általános Iskola, Gimnázium és Pedagógiai Szakgimnázium - Miskolc",
"Zafféry Károly Szalézi Középiskola - Nyergesújfalu",
"Balassi Bálint Gimnázium - Kál",
"Altisz Alapítványi Gimnázium - Budapest X. kerület",
"Patkós Irma Művészeti Iskola, Gimnázium, Szakgimnázium és AMI - Cegléd",
"HARMÓNIA Alapfokú Művészeti Iskola, Általános Iskola és Gimnázium - Nyíregyháza",
"British International School Alapítványi Óvoda, Általános- és Középiskola - Budapest III. kerület",
"Debreceni Református Kollégium Dóczy Gimnáziuma - Debrecen",
"Szikszói Szakképző Iskola és Szakgimnázium - Szikszó",
"Bethlen Gábor Gimnázium, Általános Iskola, Óvoda és Alapfokú Művészeti Iskola - Nyíregyháza",
"Pannon Oktatási Központ Gimnázium, Szakgimnázium, Technikum, Szakképző Iskola és Általános Iskola - Dunaújváros",
"Fehérlófia Waldorf Óvoda, Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Nemesvámos",
"Facultas Humán Gimnázium - Budapest VII. kerület",
"Alexandra Általános Iskola és Gimnázium - Baktalórántháza",
"Uzoni Péter Gimnázium és Általános Iskola - Salgótarján",
"Huszár Gál Gimnázium, Általános Iskola, Alapfokú Művészeti Iskola és Óvoda - Debrecen",
"Kölcsey Ferenc Gimnázium - Nyíregyháza",
"Csanádi Árpád Sportiskola, Általános Iskola és Gimnázium - Budapest XIV. kerület",
"KOCH VALÉRIA GIMNÁZIUM, ÁLTALÁNOS ISKOLA, ÓVODA, KOLLÉGIUM ÉS PEDAGÓGIAI INTÉZET - Pécs",
"Deák Ferenc Általános Iskola és Gimnázium - Zalaszentgrót",
"Friedrich Schiller Gimnázium és Kollégium - Pilisvörösvár",
"Benkő István Református Általános Iskola és Gimnázium - Budapest IV. kerület",
"Szépség- Kultúra Gimnázium és Óvoda - Győr",
"Magyar-Kínai Két Tanítási Nyelvű Általános Iskola és Gimnázium - Budapest XV. kerület",
"Dankó Pista Óvoda, Általános Iskola, Gimnázium, Szakgimnázium, Technikum, Szakképző Iskola és Kollégium - KATICA Bölcsőde - Biri",
"Forrás Felnőttoktatási Gimnázium - Szeged",
"A Tan Kapuja Buddhista Gimnázium és Általános Iskola - Pécs",
"Wesley János Óvoda, Általános Iskola és Gimnázium - Budapest X. kerület",
"Beregi Általános Iskola, Gimnázium és Technikum - Vásárosnamény",
"Magiszter Óvoda, Általános Iskola, Középiskola, Szakképző Iskola és Alapfokú Művészeti Iskola - Debrecen",
"Budapesti Montessori Általános Iskola és Gimnázium - Budapest XX. kerület",
"Gróf Batthyány Lajos Alapítványi Gimnázium, Technikum és Felnőttek Általános Iskolája - Hatvan",
"Magyarországi Japán Nagykövetséghez tartozó Budapesti Japán Iskola - Budapest XII. kerület",
"Encsi Váci Mihály Gimnázium és Kollégium - Encs",
"Ózdi József Attila Gimnázium és Kollégium - Ózd",
"Szlovák Gimnázium, Általános Iskola, Óvoda és Kollégium - Békéscsaba",
"Szent Gotthárd Általános Iskola és Gimnázium - Szentgotthárd",
"Tüskevár Általános Iskola és Gimnázium - Budapest IV. kerület",
"Bolyai János Gimnázium és Általános Iskola - Tiszakóród",
"Eszterházy Károly Egyetem Gyakorló Általános, Közép-, Alapfokú Művészeti Iskola és Pedagógiai Intézet - Eger",
"Báthori István Gimnázium - Nyírlugos",
"Testnevelési Egyetem Gyakorló Sportiskolai Általános Iskola és Gimnázium - Budapest XII. kerület",
"Halásztelki Hunyadi Mátyás Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Halásztelek",
"Sirius Gimnázium és Szakgimnázium - Debrecen",
"Leonardo Média Akadémia Gimnázium, Szakgimnázium és Általános Iskola - Nyíregyháza",
"Orchidea Magyar-Angol Két Tanítási Nyelvű Óvoda, Általános Iskola és Gimnázium - Budapest XIII. kerület",
"Gorsium Gimnázium, Szakgimnázium és Technikum - Székesfehérvár",
"SZAK-MA Általános Iskola és Gimnázium - Nyíregyháza",
"Oroszországi Föderáció Magyarországi Nagykövetség Mellett Működő Általános Iskola és Gimnázium - Budapest XIII. kerület",
"Fehér Miklós Labdarúgó Akadémia Gimnáziuma és Kollégiuma - Győr",
"II. Rákóczi Ferenc Általános Iskola és Gimnázium - Szécsény",
"Bocskai István Katolikus Gimnázium és Technikum - Szerencs",
"Németh László Gimnázium, Általános Iskola - Hódmezővásárhely",
"Bessenyei György Gimnázium - Budapest XI. kerület",
"Barcsi Széchényi Ferenc Gimnázium és Kollégium - Barcs",
"Szeged és Térsége Eötvös József Gimnázium, Általános Iskola - Szeged",
"Szegedi Baptista Gimnázium és Technikum - Szeged",
"Kecskeméti Kodály Zoltán Ének-zenei Általános Iskola, Gimnázium, Szakgimnázium és Alapfokú Művészeti Iskola - Kecskemét",
"Fekete István - Vörösmarty Mihály Általános Iskola és Gimnázium - Ajka",
"Csongrádi Batsányi János Gimnázium és Kollégium - Csongrád",
"Atilla Király Gimnázium és Általános Iskola - Aba",
"Baross Imre Artistaképző Intézet Előadó-művészeti Szakgimnázium, Gimnázium, Technikum és Alapfokú Táncművészeti Iskola - Budapest VII. kerület",
"Leonardo Gimnázium - Budapest XX. kerület",
"Dr. Ámbédkar Gimnázium, Technikum, Szakképző Iskola, Általános Iskola és Martin Luther King Középiskolai Kollégium - Miskolc",
"Wesley Kincsei Általános Iskola és Gimnázium - Budapest XVIII. kerület",
"Al Wahda Arab Iskola - Budapest XV. kerület",
"Eötvös József Gimnázium és Kollégium - Tata",
"Balázs Győző Református Gimnázium, Egységes Művészeti Szakgimnázium és Magyar - Angol Két Tanítási Nyelvű Művészeti Általános Iskola, Alapfokú Művészetoktatási Iskola - Miskolc",
"MIOK József Nádor Általános Iskola, Középiskola, Szakiskola, Technikum és Szakképző Iskola - Miskolc",
"Pécsi József Nádor Általános Iskola, Gimnázium, Szakiskola, Technikum és Szakképző Iskola - Pécs",
"Tiszavasvári Váci Mihály Gimnázium - Tiszavasvári",
"Batthyány Fülöp Gimnázium és Általános Iskola - Enying",
"Tatai Református Gimnázium - Tata",
"Qualitas Gimnázium - Budapest XXIII. kerület",
"Miskolci Magister Gimnázium - Miskolc",
"Wesley János Óvoda, Általános Iskola és Gimnázium - Szeged",
"Wesley János Óvoda, Általános Iskola, Gimnázium, Alapfokú Művészeti Iskola - Gyüre",
"Kökönyösi Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Komló",
"Tiszaparti Római Katolikus Általános Iskola és Gimnázium - Szolnok",
"Karcagi Nagykun Református Gimnázium - Karcag",
"Hajdú-Bihar Megyei Általános Iskola, Gimnázium, Szakgimnázium, Technikum és Kollégium - Debrecen",
"Brázay Kálmán Általános Iskola, Gimnázium, Szakiskola, Szakgimnázium, Technikum és Szakképző Iskola - Magyarhertelend",
"Fókusz Gimnázium és Szakképző Intézmény, Általános Iskola és Felnőttképző Intézmény - Miskolc",
"Felnőtt Oktatási Központ és Gimnázium - Budapest XIV. kerület",
"Hatvani Bajza József Gimnázium - Hatvan",
"Szalézi Szent Ferenc Gimnázium - Kazincbarcika",
"Sztehlo Gábor Evangélikus Óvoda, Általános Iskola és Gimnázium - Budapest XVIII. kerület",
"Szent János Görögkatolikus Gimnázium, Szakgimnázium, Technikum és Kollégium - Edelény",
"Bercsényi Miklós Katolikus Gimnázium és Kollégium, Általános Iskola, Óvoda - Törökszentmiklós",
"Kiskőrösi Petőfi Sándor Evangélikus Óvoda, Általános Iskola, Gimnázium és Technikum - Kiskőrös",
"Pannon Gimnázium és Általános Iskola - Vác",
"Mikes Kelemen Katolikus Gimnázium és Technikum, Általános Iskola és Óvoda - Battonya",
"Tudásfa Felnőttoktatási Gimnázium és Általános Iskola - Szigetszentmiklós",
"AUDI Hungaria Általános Művelődési Központ - Győr",
"Vajda Péter Evangélikus Gimnázium - Szarvas",
"Bernáth Kálmán Református Gimnázium, Kereskedelmi és Vendéglátóipari Technikum és Szakképző Iskola - Vác",
"Móricz Zsigmond Református Kollégium, Gimnázium, Technikum, Általános Iskola és Óvoda - Kisújszállás",
"Eötvös József Református Oktatási Központ - Óvoda, Általános Iskola, Gimnázium, Technikum, Szakképző Iskola és Alapfokú Művészeti Iskola - Heves",
"Nagykun Baptista Oktatási Központ Általános Iskola, Gimnázium, Technikum, Szakképző Iskola és Kollégium - Kisújszállás",
"Zöldliget Magyar-Angol Két Tanítási Nyelvű Baptista Általános Iskola és Gimnázium - Velence",
"Csuha Antal Baptista Általános Iskola, Gimnázium, Technikum és Szakképző Iskola - Nagyhalász",
"KOSZISZ Szent István Gimnázium és Technikum - Újfehértó",
"Petőfi Sándor Római Katolikus Általános Iskola és Gimnázium - Vecsés",
"KarrierSuli Esti Gimnázium - Budapest XIV. kerület",
"Avicenna International College Magyar-Angol Két Tanítási Nyelvű Gimnázium - Budapest VIII. kerület",
"QSI Nemzetközi Iskola Magyarország - Pápa",
"Tiszta Forrás Waldorf Általános Iskola,Gimnázium, Alapfokú Művészeti Iskola és Óvoda - Kiskunfélegyháza",
"Csillagberek Waldorf Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Budapest IV. kerület",
"Páter Bárkányi János Katolikus Óvoda, Általános Iskola és Gimnázium - Szécsény",
"Báró Wesselényi Miklós Alapítványi Általános Iskola,Gimnázium, Technikum és Alapfokú Művészeti Iskola - Balatonfűzfő",
"Gomba Levente Gimnázium - Putnok",
"Árpád Fejedelem Katolikus Gimnázium és Technikum - Kistelek",
"Göllner Mária Regionális Waldorf Gimnázium és Alapfokú Művészeti Iskola - Budapest IV. kerület",
"Kálvin János Református Gimnázium, és Általános Iskola - Dunaújváros",
"Fehér Vár Waldorf Óvoda, Általános Iskola, Gimnázium és Alapfokú Művészeti Iskola - Székesfehérvár",
"Tamási Béri Balogh Ádám Katolikus Gimnázium, Kollégium, Általános Iskola és Óvoda - Tamási",
"TANDEM Gimnázium - Budapest I. kerület",
"Kőrösi Csoma Sándor Református Gimnázium - Hajdúnánás",
"Diákszempont Általános Iskola és Gimnázium - Budapest VI. kerület",
"Tomori Pál Katolikus Gimnázium, Technikum és Kollégium - Kiskunmajsa",
"Szent Márton Katolikus Gimnázium és Általános Iskola - Szikszó",
"Alternatíva Életfa Általános Iskola, Gimnázium, Művészeti Szakgimnázium és Alapfokú Művészeti Iskola - Miskolc",
"Bátaszéki II. Géza Gimnázium - Bátaszék",
"Nyíregyházi RIDENS Gimnázium, Szakgimnázium, Szakiskola és Kollégium - Nyíregyháza",
"Pécsi Árpád Fejedelem Gimnázium és Általános Iskola - Pécs",
"Veresegyházi Katolikus Gimnázium - Veresegyház",
"Maimonidész Zsidó Gimnázium - Budapest III. kerület",
"Cserepka János Magyar-Angol Két Tanítási Nyelvű Baptista Sportiskola, Általános Iskola, Gimnázium és Technikum - Pécs",
"Budapest British International School Angol Általános Iskola és Gimnázium - Budapest XII. kerület",
"Szabad Waldorf Gimnázium és Alapfokú Művészeti Iskola - Budapest XI. kerület",
"Ibrányi Református Óvoda, Általános Iskola, Gimnázium és Kollégium - Ibrány",
"Balatonfüredi Szent Benedek Gimnázium, Technikum, Szakképző Iskola és Kollégium - Balatonfüred",
"Debreceni Nemzetközi Iskola - Debrecen",
"Veritas Collegiate Academy Budapest Gimnázium - Budapest III. kerület",
"Tanház Gimnázium és Technikum - Békéscsaba",
"Kölcsey Ferenc Baptista Általános Iskola, Gimnázium, Technikum, Szakképző Iskola és Kollégium - Nyíradony",
"Maarif Magyar-Angol Két Tanítási Nyelvű Általános Iskola és Gimnázium - Budapest IX. kerület",
"Kecskeméti Németh László Gimnázium - Kecskemét",
"Dunaföldvári Magyar László Gimnázium - Dunaföldvár",
"Matúra Gimnázium - Budapest VI. kerület",
"Szent Miklós Görögkatolikus Gimnázium és Kollégium - Nyíregyháza",
"Adventum Iskola - Budapest XI. kerület",
"Tempus Felnőttek Általános Iskolája és Gimnáziuma - Ecser",
"Budapest School Általános Iskola és Gimnázium - Budapest XIII. kerület",
"CREASCOLA Nyolcosztályos Gimnázium - Budaörs",
"Illés Labdarúgó Akadémia Gimnáziuma és Kollégiuma - Szombathely",
"Szent Ágoston Keresztény Általános Iskola és Gimnázium - Fót",
"Szent Benedek Gimnázium és Technikum - Budapest VIII. kerület",
"Gyermekek Háza Alternatív Általános Iskola és Gimnázium - Budapest II. kerület",
"Jászapáti Gróf Széchenyi István Katolikus Gimnázium - Jászapáti"].sort();